### ISSUE TITLE
Updates coming for Bitbucket Server 6?

### ISSUE THREAD

**Issue by robsonke** [Tuurlijk/bitbucket-chainsaw#1]
Hi Michiel,

We enjoyed your plugin a lot till it recently stopped working in BB6. I saw a recent commit where you were updating versions but it seems it's not compatible yet.

Any plans for compatibility changes or any help required?

**Comment by Tuurlijk** [comment]
Hi,

Glad to hear that you enjoyed it. The last commit was to make the plugin 'build' in the sdk. But the JavaScript libraries seem to have changed since I last looked (v4). So the JavaScript libraries will need to be brought to the naming used in v6.

Do you hav experience with that? Patches are welcome.

**Comment by robsonke** [comment]
Not really, I took a two seconds look but will try to dive in deeper.

**Comment by robsonke** [comment]
Fixed the plugin, had to do quite some changes as they removed all their internal apis. At least it works again now

**Comment by Tuurlijk** [comment]
Hey Rob,

Bedankt voor je patch! Werkt. Ik zag alleen dat de takken die je gaat verwijderen niet meer getoond worden in het bevestigingsberichtje / modal.

Heb versie 1.2.0 geupload naar de marketplace.

Ik heb de atlassian marketplace beheerders gevraagd om mijn plugins te unhiden nu ze allemaal zijn bijgewerkt.

**Comment by robsonke** [comment]
Ja, hij list je branches niet meer. Kan ik nog wel bijbouwen maar die hele dialog is op de schop gegaan dus dit was makkelijker.
Bedankt voor de snelle merge.
